"""Fixes

Revision ID: 02220cfbf894
Revises: 3130d18d33ef
Create Date: 2025-02-10 22:27:48.440254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02220cfbf894'
down_revision = '3130d18d33ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        # Add 'views' column with a default value of 0
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
