"""Add views relationship user and song models

Revision ID: 3130d18d33ef
Revises: 8831ea147abd
Create Date: 2025-02-10 22:21:22.769734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3130d18d33ef'
down_revision = '8831ea147abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
