"""Reinit migrations

Revision ID: 9f62d688f374
Revises: 
Create Date: 2025-02-10 22:03:22.029027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f62d688f374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        # Add the 'views' column with a default value of 0
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
